### ISSUE TITLE
Trained model sharing and questions on test module

### ISSUE THREAD

**Issue by JunMa11** [MIC-DKFZ/basic_unet_example#4]
Dear MIC-DKFZ,

Thanks for the great respo. I'm a pytorch starter, and I'm using this U-Net example as a beginning.
Enviroment: Ubuntu 16.0, Titan XP, pytorch 1.0, batchgenerators 0.19

- Following the guideline, the 2D training process works well. The trained model can be found [here](https://drive.google.com/open?id=1yBSDbbkwySSv0OlHcaN5ZDoEBksRpNHu).

- The 3D training process also works but we need to modify the loggers in `train3D.py` as 2D case.  [Trained model of 3D U-Net](https://drive.google.com/open?id=1yBSDbbkwySSv0OlHcaN5ZDoEBksRpNHu)

```python
loggers={ "visdom": ("visdom", {"auto_start": c.start_visdom})}
```
   
- [batchgenerators](https://github.com/MIC-DKFZ/batchgenerators) 0.19 released recently. I use the new verson and it works well. `pytorch 1.0` also works well. So the `requirements.txt` may be updated.

The test module in [experiments](https://github.com/MIC-DKFZ/basic_unet_example/blob/master/experiments) does not implement. It is a litter difficult for pytorch beginners to finish it. **Would it be possible for you to complete the test module in [U-Net 2D and 3D](https://github.com/MIC-DKFZ/basic_unet_example/tree/master/experiments) at your convenience? So this respo will be a complete U-Net example.**

I think it is worth to enrich this great respo and make it to be a good begining/tutorial for pytorch starters in medical image segmentation, becuase I do not find such starter-friendly respo in github. Most of the U-Net respos are for CV rather than for medical image segmentation.
Although I can not contribute the valuable code now, I can do the code testing work and share the trained model.

Looking forward to your reply!
Best,
Jun

**Comment by elpequeno** [comment]
Hi @JunMa11,

thank you for sharing your experience with our repo. I think I can provide an example "test()" method in the future. I'm on vacation for the next 2 weeks, but maybe after that.
Thank you for testing the newest versions of the imported frameworks. I'll update the requirements.txt accordingly.

I'll contact you again in about 2 weeks.
Cheers,
André

**Comment by JunMa11** [comment]
Hi @elpequeno ,
Thanks for your quick reply and approval. 
I wish you a very good journey.

**Comment by elpequeno** [comment]
Thank you :-D
You are welcome.
If you want to practice a little since you say you are a beginner: The test() method will look similar to the validation. You need to load your test data, iterate over them and calculate the metrics you are interested in. For a start, I would say DICE, IOU, precision, and recall. Of cause, there are many more, but that sounds like a good start for me.

**Comment by JunMa11** [comment]
Thanks for your guidance. I will try it.

**Comment by elpequeno** [comment]
I added a test method to the 2D UNetExperiment. Results are printed in the terminal and also stored in a JSON file.
Check it out and tell me if this helps. I'll close this task.

**Comment by JunMa11** [comment]
Get it.
Thank you very much.
