### ISSUE TITLE
improve the requirement.txt

### ISSUE THREAD

**Issue by jizongFox** [MIC-DKFZ/basic_unet_example#6]
The `slackclient==2.0.0` might be needed for a fresh run.

**Comment by elpequeno** [comment]
Hi Jizong,

thank you for your suggestion. Is there a specific scenario you are referring to that you need slackclient==2.0.0 for?
The basic_unet_example does not list slackclient as a requirement at the moment. As far as I know, trixi uses slackclient. If there is an issue shouldn't the dependency be updated there? Correct me if I'm wrong. 

Pura vida,
André

**Comment by jizongFox** [comment]
Following the basic_unet_example instruction, after having created a virtual env, installed the requirements, the launch script raises an error of not finding that dependency. If the case can be reproducible, that can be an issue for trixi.
Anyway, thanks for these wonderful jobs.

**Comment by elpequeno** [comment]
I'll test it again. Not sure if I can do it today, but I'll let you know. Thank's for pointing it out.

**Comment by elpequeno** [comment]
Hi Jizong,

I just tested in on a fresh virtualenv. I had no problems whatsoever. I used `pip install -r requirements.txt`. 
Which script raises the error for you? Can you please provide the error message?

Pura vida,
André

**Comment by elpequeno** [comment]
Hi Jizong,

I just reproduced it on a colleagues machine. I'll investigate further.
